### PR TITLE
Update for Foundry version 9

### LINKED ISSUE #29: No longer working in V9
The issue seems to be that it doesn't register X in the new Keybindings API

keybindings.js:104 Uncaught TypeError: game.keyboard.getKey is not a function
[Detected 1 package: pointer]
    at checkKey (keybindings.js:104)
    at onPointerDown (keybindings.js:123)
checkKey @ keybindings.js:104
onPointerDown @ keybindings.js:123

However also the Pointer with long press doesn't seem to work.

### PR DESCRIPTION
**Pull request by spaceotter**
Changes the keybinding method to the new ClientKeybindings system. This
unfortunately prevents binding the ping to a mouse click.

Resolves #29 .

### CODE REVIEW

**Comment by spaceotter** [comment]
It should be possible to enable the mouse option again with some extra checkbox or something, it would be a bit cumbersome.

**Comment by Moerill** [comment]
Thanks for the work!

But not having the mouse as option sounds kind of bad to me - it'd be kind of important to me to keep that functionality.  
Isn't it possible to just defer the keypress event to the new keybinding system instead of a DOM event? shouldn't that kind of keep everything the way it was? Or is the keybind system to limiting for this?

**Comment by spaceotter** [comment]
The suggestion was to use a keybinding to toggle a variable and then trigger pings from the mouse API. So there could be a checkbox that switches that on.
Also there is some issue with the localization not appearing in the keybinding gui. I'll see what can be done.

**Comment by Moerill** [comment]
Integrated your other PR. Thanks again for this!!

**Pull request closed without merging**
